"""add_derived_user_id

Revision ID: 4bee758ca41e
Revises: 7c47273e8371
Create Date: 2026-06-06 22:02:22.187097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bee758ca41e'
down_revision: Union[str, Sequence[str], None] = '7c47273e8371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('derived_user_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_transactions_derived_user_id'), 'transactions', ['derived_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_derived_user_id'), table_name='transactions')
    op.drop_column('transactions', 'derived_user_id')
    # ### end Alembic commands ###
